// <auto-generated />
using CheckOutChampionWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckOutChampionWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckOutChampionWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Clothing & Apparel"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Toys & Games"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
